version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      compatible-updates:
        update-types: [minor, patch]
  - package-ecosystem: uv
    directory: /evals-py
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      compatible-updates:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      compatible-updates:
        update-types: [minor, patch]

